# write a program to input eight numbers from the user and display all unique numbers once 
s = set()
n = input("enter the number1: ")
s.add(int(n))
n = input("enter the number2: ")
s.add(int(n))
n = input("enter the number3: ")
s.add(int(n))
n = input("enter the number4: ")
s.add(int(n))
n = input("enter the number5: ")
s.add(int(n))
n = input("enter the number6: ")
s.add(int(n))
n = input("enter the number7: ")
s.add(int(n))
n = input("enter the number8: ")
s.add(int(n))
print(s)